In [1]:
!pip install torch==1.0.1 torchvision==0.2.2

In [2]:
import nltk

In [3]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading packag

True

In [4]:
import numpy as np
import pandas as pd

In [5]:
dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/Restaurant_Reviews.tsv.txt', delimiter= '\t', quoting = 3)

In [6]:
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [7]:
from nltk.corpus import stopwords


In [8]:
from nltk.stem.porter import PorterStemmer


In [9]:
ps = PorterStemmer()


In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [11]:
corpus = []


In [12]:
import re

In [13]:
for i in range(0, 1000):

  customer_review = re.sub('[^a-zA-Z]', ' ',dataset['Review'][i])
  customer_review = customer_review.lower()
  customer_review = customer_review.split()
  clean_review = [ps.stem(word) for word in customer_review if not word in set(stopwords.words('english'))]
  clean_review = ' '.join(clean_review)
  corpus.append(clean_review)

In [14]:
corpus[0]

'wow love place'

In [15]:
corpus[6]

'honeslti tast fresh'

In [16]:
corpus[12]

'cashier care ever say still end wayyy overpr'

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features = 1500, min_df = 3, max_df = 0.6)


In [18]:
X = vectorizer.fit_transform(corpus).toarray()


In [19]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
X[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [21]:
y = dataset.iloc[:, 1].values

In [22]:
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [24]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [25]:
print(torch.__version__)

1.0.1


In [26]:
Xtrain_ = torch.from_numpy(X_train).float()
Xtest_ = torch.from_numpy(X_test).float()

In [27]:
ytrain_ = torch.from_numpy(y_train)
ytest_ = torch.from_numpy(y_test)

In [28]:
Xtrain_.shape, ytrain_.shape

(torch.Size([800, 467]), torch.Size([800]))

In [29]:
Xtest_.shape, ytest_.shape

(torch.Size([200, 467]), torch.Size([200]))

In [30]:
input_size=467
output_size=2
hidden_size=500

In [31]:
class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size)
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
       self.fc3 = torch.nn.Linear(hidden_size, output_size)


   def forward(self, X):
       X = torch.relu((self.fc1(X)))
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)

       return F.log_softmax(X,dim=1)

In [32]:
model = Net()


In [33]:
import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()

In [34]:
epochs = 100


In [35]:
for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred = model(Xtrain_)
  loss = loss_fn(Ypred,  ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch',epoch, 'loss',loss.item())

Epoch 0 loss 0.6933408379554749
Epoch 1 loss 0.6712999939918518
Epoch 2 loss 0.5471299886703491
Epoch 3 loss 0.35765624046325684
Epoch 4 loss 0.2313990592956543
Epoch 5 loss 0.16735348105430603
Epoch 6 loss 0.10427160561084747
Epoch 7 loss 0.09019485116004944
Epoch 8 loss 0.07943294942378998
Epoch 9 loss 0.06255828589200974
Epoch 10 loss 0.045051902532577515
Epoch 11 loss 0.044423364102840424
Epoch 12 loss 0.04883534461259842
Epoch 13 loss 0.039201803505420685
Epoch 14 loss 0.03475183621048927
Epoch 15 loss 0.03639525547623634
Epoch 16 loss 0.03609052672982216
Epoch 17 loss 0.03316528722643852
Epoch 18 loss 0.03137346729636192
Epoch 19 loss 0.030696826055645943
Epoch 20 loss 0.03220561146736145
Epoch 21 loss 0.03090761974453926
Epoch 22 loss 0.029216811060905457
Epoch 23 loss 0.029901456087827682
Epoch 24 loss 0.030969781801104546
Epoch 25 loss 0.0293154064565897
Epoch 26 loss 0.02872937172651291
Epoch 27 loss 0.02999374456703663
Epoch 28 loss 0.029383979737758636
Epoch 29 loss 0.02871

In [36]:
sample = ["Good batting by England"]


In [37]:
sample = vectorizer.transform(sample).toarray()


In [38]:
sample

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [39]:
torch.from_numpy(sample).float()

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.,

In [40]:
sentiment = model(torch.from_numpy(sample).float())
sentiment

tensor([[-2.0209, -0.1422]], grad_fn=<LogSoftmaxBackward>)

In [41]:
sample2 = ["bad performance by India in the match"]


In [42]:
sample2 = vectorizer.transform(sample2).toarray()


In [43]:
sentiment2 = model(torch.from_numpy(sample2).float())
sentiment2

tensor([[  0.0000, -44.1050]], grad_fn=<LogSoftmaxBackward>)

In [44]:
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.0940, -0.0413, -0.0656,  ...,  0.0897, -0.0869,  0.1392],
                      [-0.0197, -0.0816, -0.1059,  ...,  0.0228,  0.1195, -0.1405],
                      [ 0.0237,  0.0054, -0.0162,  ...,  0.0025,  0.0080, -0.0223],
                      ...,
                      [-0.0354, -0.0016, -0.0252,  ...,  0.0052,  0.0607,  0.0114],
                      [-0.0611,  0.0420, -0.1292,  ..., -0.0420, -0.0125,  0.0076],
                      [-0.0167, -0.0350, -0.1169,  ...,  0.0250,  0.1192, -0.0812]])),
             ('fc1.bias',
              tensor([ 1.1780e-02,  1.1869e-02, -7.3322e-03, -1.0564e-01, -1.0328e-01,
                      -6.5869e-03,  5.4558e-03, -5.6038e-02, -7.7382e-02, -5.4056e-02,
                       2.0714e-02,  3.7538e-02, -5.9266e-02,  2.1252e-02, -1.0462e-03,
                       6.7312e-03,  6.5557e-02,  4.6935e-02,  1.3896e-02,  4.8566e-02,
                       3.0712e-02,  2.4049e-02, -3.4352e-03, -1.

In [45]:
torch.save(model.state_dict(),'text_classifier_pytorch')

In [46]:
!ls

sample_data  text_classifier_pytorch


In [47]:
from google.colab import files


In [48]:
files.download('text_classifier_pytorch')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [49]:
import pickle

In [ ]:
with open('tfidfmodel.pickle','wb') as file:
    pickle.dump(vectorizer,file)

In [ ]:
files.download('tfidfmodel.pickle')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>